# Generated by Django 5.1.5 on 2025-01-22 19:42

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0007_prompttemplate_safety_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegenerationrequest',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='generated/'),
        ),
        migrations.AlterField(
            model_name='imagegenerationrequest',
            name='seed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2147483648), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='imagegenerationrequest',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='thumbnails/'),
        ),
    ]
